server:
  port: 20001

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  application:
    name: VA

  datasource:
    url: ""
    username: ""
    password: ""

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
