server:
  port: 20001

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  application:
    name: VA

  datasource:
    url: "jdbc:mysql://localhost:3306/virtual_account"
    username: "root"
    password: "passw0rd"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
